name: Publish Docker Images
run-name: Publish Docker Images 🚀
on: 
  push:
    branches: 
      - main
jobs:
  publish-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/msxmarten/build-containers/opentofu
          tags: |
            latest

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: opentofu-1.7.0
          push: true
          tags: ${{ steps.meta.outputs.tags }}
