name: Publish Docker Images
run-name: Publish Docker Images 🤠🐳
on: 
  push:
    branches: 
      - main
jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout 
        uses: actions/checkout@v4

      - name: Set matrix for build
        id: set-matrix
        # run: |
        #   DOCKERFILES=$(find . -name Dockerfile | cut -d "/" -f2 | sed ':a;N;$!ba;s/\n/","/g')
        #   DOCKERFILES_JSON="\"$DOCKERFILES\""
        #   echo "::set-output name=matrix::{\"dockerfile\":[$DOCKERFILES_JSON]}"
        shell: pwsh
        run: |
          $dockerfileObject = @{
            "include" = @()
          }
          $DOCKERFILES = (Get-ChildItem -Recurse -Filter Dockerfile | ForEach-Object { $_.DirectoryName.Split("/")[6] })
          foreach ($DOCKERFILE in $DOCKERFILES) {
            $tags = Get-Content "./$DOCKERFILE/tags.json" | ConvertFrom-Json
            foreach ($tag in $tags.tags) {
              $dockerfileObject["include"] += @{
                "directory" = $DOCKERFILE
                "name" = $DOCKERFILE -split "-" | Select-Object -First 1
                "tag" = "type=raw,value=$tag"
              }
            }
          }
          $dockerfileJson = $dockerfileObject | ConvertTo-Json -Compress
          echo "::set-output name=matrix::$dockerfileJson"
          Write-Output $dockerfileJson

  publish-image:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.prepare.outputs.matrix) }}
    steps:
      - name: Checkout 
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/msxmarten/build-containers/${{ matrix.name }}
          tags: |
            ${{ matrix.tag }}


      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.directory }}
          push: true
          tags: |
            ${{ steps.meta.outputs.tags }}