name: Publish Docker Images
run-name: Publish Docker Images 🚀
on: 
  push:
    branches: 
      - main
jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout 
        uses: actions/checkout@v4

      - name: Set matrix for build
        id: set-matrix
        # run: |
        #   DOCKERFILES=$(find . -name Dockerfile | cut -d "/" -f2 | sed ':a;N;$!ba;s/\n/","/g')
        #   DOCKERFILES_JSON="\"$DOCKERFILES\""
        #   echo "::set-output name=matrix::{\"dockerfile\":[$DOCKERFILES_JSON]}"
        shell: pwsh
        run: |
          $DOCKERFILES = (Get-ChildItem -Recurse -Filter Dockerfile | ForEach-Object { $_.DirectoryName.Split("/")[6] }) -join '","'
          echo $DOCKERFILES
          $DOCKERFILES_JSON = "`"$DOCKERFILES`""
          echo "::set-output name=matrix::{`"dockerfile`":[$DOCKERFILES_JSON]}"

  publish-image:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.prepare.outputs.matrix) }}
    steps:
      - name: Checkout 
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Parse tags
        id: parse
        run: |
          TAGS=$(jq -r '.tags | join(",")' ${{ matrix.dockerfile }}/tags.json)
          TAGS=$(echo $TAGS | awk 'BEGIN{RS=","; OFS=","} {print "type=raw,value="$1}')
          echo "::set-output name=tags::$TAGS"
          NAME=$(echo ${{ matrix.dockerfile}} | cut -d"-" -f1)
          echo "::set-output name=name::$NAME"
      
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/msxmarten/build-containers/${{ steps.parse.outputs.name }}
          tags: |
            ${{ steps.parse.outputs.tags }}


      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.dockerfile }}
          push: true
          tags: |
            ${{ steps.meta.outputs.tags }}
