name: Dynamic Matrix Pipeline

on:
  push:
    branches:
      - main

jobs:
  prepare-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.create-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create matrix
        id: create-matrix
        run: |
          MATRIX_JSON=$(jq -n '{
            "include": [
              {
                "name": "terraform",
                "tags": "latest"
              },
              {
                "name": "opentofu",
                "tags": "latest"
              }
              # Add more dynamic entries as needed
            ]
          }')
          echo "::set-output name=matrix::$MATRIX_JSON"

  publish-image:
    needs: prepare-matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.prepare-matrix.outputs.matrix)}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/msxmarten/build-containers/${{ matrix.name }}
          tags: |
            ${{ matrix.tags }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.name }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}